/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-tertiary': '#ffffff',
        'tertiary-fixed-dim': '#cec89a',
        'outline': '#717a6c',
        'on-primary': '#ffffff',
        'surface-dim': '#dedacd',
        'tertiary-container': '#b2ad81',
        'on-secondary-container': '#34712d',
        'primary-container': '#0d530e',
        'inverse-surface': '#323128',
        'on-error-container': '#93000a',
        'surface-container-lowest': '#ffffff',
        'primary-fixed': '#acf59d',
        'secondary-fixed-dim': '#94d786',
        'background': '#fdf9eb',
        'secondary-fixed': '#b0f49f',
        'surface-bright': '#fdf9eb',
        'error-container': '#ffdad6',
        'surface-container-high': '#ece8da',
        'error': '#ba1a1a',
        'surface-variant': '#e6e2d5',
        'primary': '#003a03',
        'inverse-on-surface': '#f5f1e3',
        'surface-container-low': '#f7f4e6',
        'surface-container': '#f2eee0',
        'surface-tint': '#2a6c25',
        'on-tertiary-container': '#44411e',
        'tertiary-fixed': '#eae4b4',
        'secondary-container': '#b0f49f',
        'on-tertiary-fixed': '#1f1c01',
        'on-surface': '#1c1c14',
        'on-secondary': '#ffffff',
        'inverse-primary': '#91d883',
        'on-background': '#1c1c14',
        'surface': '#fdf9eb',
        'primary-fixed-dim': '#91d883',
        'on-primary-container': '#81c674',
        'outline-variant': '#c0c9b9',
        'on-surface-variant': '#41493d',
        'on-error': '#ffffff',
        'secondary': '#2e6b27',
        'surface-container-highest': '#e6e2d5',
        'tertiary': '#63603a',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      fontFamily: {
        sans: ['Arimo', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', fontWeight: '600' }],
        'caption': ['12px', { lineHeight: '16px', fontWeight: '400' }],
      },
      spacing: {
        'lg': '48px',
        'xl': '80px',
        'md': '24px',
        'sm': '12px',
        'base': '8px',
        'xs': '4px',
        'gutter': '24px',
        'margin-desktop': '64px',
        'margin-mobile': '16px',
      },
    },
  },
  plugins: [],
};
